server:
  port: 8081
spring:
  application:
    name: user-pref-read-service
  data:
    mongodb:
      host: ${MONGO_HOST:mongodb}
      port: ${MONGO_PORT:27017}
      database: "user-pref"
      auto-index-creation: true
  redis:
    host: redis
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
